	<div><h3 align="center">Giới Thiệu</h3>
	Trường Đại học An Giang được thành lập theo Quyết định số 241/1999/QĐ-TTg, ngày 30 tháng 12 năm 1999 của Thủ tướng Chính phủ và khai giảng năm học đầu tiên ngày 09 tháng 9 năm 2000. Xây dựng trên cơ sở Trường Cao đẳng Sư phạm An Giang, Trường Đại học An Giang là cơ sở đào tạo công lập trong hệ thống các trường đại học Việt Nam, chịu sự quản lý chuyên môn của Bộ Giáo dục và Đào tạo, đồng thời chịu sự quản lý trực tiếp của Ủy ban nhân dân tỉnh An Giang. Trường có nhiệm vụ đào tạo trình độ đại học, phục vụ nhu cầu phát triển kinh tế - xã hội của tỉnh An Giang và vùng Đồng bằng sông Cửu Long. Ngoài ra Trường còn có nhiệm vụ nghiên cứu, ứng dụng và chuyển giao công nghệ trong Vùng

Năm học 2000 – 2001, nhà trường tuyển sinh khóa đầu tiên. Trong năm đầu tiên này chỉ có 5 ngành hệ đại học, đến nay nhà trường có 36 ngành đại học hệ chính quy. Ngoài ra, mỗi năm Trường còn đào tạo một số ngành Sư phạm trình độ cao đẳng và trung cấp chuyên nghiệp (tổng số có 48 ngành đào tạo hệ chính quy). Từ năm 2012, Trường không tiếp tục đào tạo trình độ trung cấp chuyên nghiệp. Thí sinh dự thi tuyển sinh hàng năm tăng dần, có năm trên 21.000 (năm 2008). Năm 2012, tỷ lệ thí sinh dự thi tuyển sinh là 85,5%, là năm có tỷ lệ thí sinh dự thi cao nhất từ trước đến nay. Đây là tín hiệu đáng mừng của một trường mới được thành lập, cho thấy sự ra đời của Trường Đại học An Giang là nhu cầu thật sự ở Đồng bằng sông Cửu Long. Từ năm học 2005 - 2006, nhà trường chính thức tuyển sinh đào tạo hệ không chính quy với hình thức vừa làm vừa học, đến nay trường đã có 04 khoá tốt nghiệp.

Trường Đại học An Giang ra đời trong giai đoạn thế giới chuyển sang thế kỷ 21. Thế kỷ có những chuyển biến to lớn, đó là lấy “Học thường xuyên, học suốt đời” làm nền tảng, dựa trên tiêu chí chung là “Học để biết, học để làm, học để cùng chung sống với nhau và học để làm người”. Là một trường có tuổi đời còn khá trẻ, đó cũng là thuận lợi để sớm bắt nhịp với yêu cầu của thời đại và lựa chọn ngành nghề mũi nhọn để đào tạo như Công nghệ sinh học, Phát triển nông thôn, Kinh tế đối ngoại, Quản trị kinh doanh, Công nghệ thực phẩm, Công nghệ thông tin, tiếng Anh... Tháng 8 năm 2004, Trường đã có sinh viên đại học tốt nghiệp, đến nay được 9 khóa tốt nghiệp với trên 8.800 sinh viên. Hiện nay, sinh viên do Trường đào tạo đã có mặt khắp vùng Đồng bằng sông Cửu Long, ở Thành phố Hồ Chí Minh và một số tỉnh thành khác trên mọi miền đất nước, mỗi người một vị trí công tác khác nhau, nhiều người đã hoàn thành chương trình sau đại học và đang tiếp tục phát huy chuyên môn, nghiệp vụ của mình.

Năm học 2009 – 2010, đánh dấu một bước phát triển mới của Trường Đại học An Giang sau 10 năm thành lập. Đây là năm học đầu tiên chuyển đổi toàn bộ hệ đào tạo chính quy từ niên chế sang học chế tín chỉ; đồng thời triển khai thực hiện kiểm định chất lượng, tổ chức lấy ý kiến phản hồi của người học về hoạt động giảng dạy của giảng viên; Trường Phổ thông Thực hành Sư phạm khai giảng năm học đầu tiên; khu trường mới (40 ha) đã đưa vào sử dụng với trang thiết bị tương đối đồng bộ. Năm học 2011 – 2012, Trường triển khai đào tạo sau đại học, bước đầu thực hiện liên kết với các trường đại học trong nước, bước tiếp theo tự mở ngành đào tạo.

Đáp ứng nhu cầu công tác đào tạo, đội ngũ cán bộ, giảng viên, công nhân viên của Trường đã không ngừng tăng lên cả về số lượng lẫn chất lượng. Những ngày đầu thành lập, Trường chỉ có 190 cán bộ, công chức, gần 40 người có trình độ Thạc sỹ, Tiến sỹ. Đến nay, Trường đã có 864 cán bộ, viên chức, trong đó trình độ Thạc sỹ, Tiến sỹ là 354 người, trên 100 người đang theo học các lớp sau đại học trong và ngoài nước (bình quân mỗi năm có trên 25 cán bộ, giảng viên hoàn thành chương trình sau đại học), có 62 giảng viên chính. Hiện nay, tỷ lệ giảng viên có trình độ sau đại học đạt 55% trên tổng số giảng viên trực tiếp giảng dạy.

Nhà trường có đầy đủ các tổ chức chính trị, chính trị xã hội. Đảng bộ với 29 chi bộ trực thuộc (605 đảng viên); 15 Công đoàn bộ phận trực thuộc Công đoàn cơ sở; tổ chức Đoàn Thanh niên, Hội Sinh viên, Hội Cựu Chiến binh, Hội Cựu Giáo chức. Hoạt động của các tổ chức đoàn thể đóng góp một phần đáng kể cho sự phát triển nhà trường trong thời gian qua. Phong trào học sinh-sinh viên tác động tích cực đến tư tưởng, tình cảm của sinh viên, được dư luận xã hội đánh giá cao và thu hút được sự ủng hộ về vật chất, tinh thần của các tầng lớp trong xã hội. Những năm gần đây, mỗi năm Trường nhận trên 1 tỷ đồng học bổng tài trợ cho sinh viên nghèo, vượt khó học tốt. Nhà trường duy trì tốt phong trào văn hóa, văn nghệ, thể dục - thể thao, nhiều năm liền đạt thứ hạng cao qua hội thi, hội thao cấp khu vực và quốc gia. Thực hiện có hiệu quả phong trào xã hội hóa giáo dục. Đã có 7 huyện thị xây dựng ký túc xá trong khuôn viên trường và một Công ty tư nhân đầu tư xây dựng Khu Ký túc xá 2.800 chỗ trong khuôn viên trường mới, hiện nay đã đưa vào khai thác giai đoạn 1 với trên 1.000 chỗ ở. Lãnh đạo nhà trường luôn tạo mọi điều kiện thuận lợi để cán bộ, công chức và học sinh - sinh viên phát huy dân chủ, lấy “Lợi ích tập thể” làm mục tiêu để phấn đấu; đảm bảo đối xử bình đẳng, công bằng; nhận xét, đánh giá chính xác, khách quan và đúng khả năng từng đối tượng trong Trường.

Xác định được tầm quan trọng của quan hệ quốc tế, hợp tác với các đơn vị trong và ngoài nước để thực hiện công tác đào tạo, nâng cao năng lực chuyên môn cho cán bộ, giảng viên, đầu tư phát triển cơ sở vật chất. Trong những năm qua, nhà trường có nhiều cố gắng mở rộng quan hệ quốc tế, đến nay đã thiết lập quan hệ và ký kết nhiều bản ghi nhớ với các trường đại học, các tổ chức nước ngoài khu vực Đông Nam Á, châu Á, châu Mỹ, châu Âu, châu Phi... Bình quân mỗi năm có khoảng 8 chuyên gia nước ngoài (tình nguyện viên) làm việc tại Trường. Từ quan hệ hợp tác quốc tế, nhà trường đã thực hiện được nhiều dự án, chương trình nghiên cứu phát triển, tạo điều kiện cho nhiều cán bộ, giảng viên tham quan, hội thảo, học tập nâng cao chuyên môn tại nước ngoài. Sự hỗ trợ nhiệt tình và có hiệu quả của các viện, trường trong khu vực thời gian qua đã giúp nhà trường vượt qua những khó khăn ban đầu về lực lượng giảng viên, về cơ sở thực hành thí nghiệm, kinh nghiệm quản lý...

Nghiên cứu khoa học là một trong hai nhiệm vụ quan trọng được nhà trường quan tâm nhằm nâng cao chất lượng giáo dục và đào tạo. Ngay từ khi thành lập, nhà trường đã áp dụng hàng loạt chế độ chính sách ưu đãi cho cán bộ, giảng viên và sinh viên để khuyến khích nghiên cứu khoa học, chuyển giao công nghệ. Đến nay, nhà trường thực hiện được 345 đề tài nghiên cứu khoa học (293 đề tài cấp trường), tham gia thực hiện quy hoạch phát triển kinh tế - xã hội theo đề nghị của một số huyện trong và ngoài tỉnh. Từ năm 2004 đến nay, mỗi năm có trên 300 đề tài nghiên cứu khoa học của sinh viên đại học chủ yếu ở loại hình khóa luận tốt nghiệp.

Trong một thời gian ngắn (27 tháng) khởi công xây dựng cơ sở mới. Tháng 3/2009, nhà trường đã đưa vào sử dụng phục vụ công tác giảng dạy và học tập; tháng 4/2010, đưa vào sử dụng khu nhà Hiệu bộ với thiết kế hiện đại, phù hợp với xu thế phát triển trong tương lai; nơi học, nơi làm việc, khu thí nghiệm, khu giảng đường... khá đầy đủ trang thiết bị, đảm bảo cơ bản nhu cầu đào tạo. Đây là điều kiện thuận lợi cơ bản để nhà trường thực hiện sứ mệnh và mục tiêu phát triển trong tương lai. Hiện tại, Trường có 2 cơ sở với tổng diện tích 48,4 ha (cơ sở cũ 8,9 ha, cơ sở mới 39,5 ha). Đến nay, cơ sở hạ tầng tại các cơ sở tương đối hoàn chỉnh, Thư viện mới được hình thành theo tiêu chí thư viện điện tử với 1.200 máy tính nối mạng, thực hiện xã hội hóa khu liên hợp thể dục, thể thao tại khu trường mới, bổ sung máy móc thiết bị khu thí nghiệm, tiếp tục bổ sung trang thiết bị dạy học tiên tiến, đẩy mạnh ứng dụng công nghệ thông tin ... Đội ngũ cán bộ, viên chức nhất là cán bộ giảng dạy được chuẩn hóa trình độ chuyên môn nghiệp vụ theo quy định của Điều lệ trường đại học; thực hiện đổi mới nội dung chương trình đào tạo, cải tiến phương pháp dạy - học, thực hiện mạnh mẽ mục tiêu đổi mới quản lý giáo dục đại học, đa dạng hóa loại hình đào tạo, tăng cường công tác đảm bảo chất lượng, duy trì hệ thống quản lý chất lượng theo tiêu chuẩn ISO 9001: 2008, áp dụng chương trình “5S”; đã và đang thực hiện các giải pháp đồng bộ nhằm đảm bảo cam kết chất lượng đào tạo.

Hiện tại, nhà trường đang tập trung củng cố tổ chức bộ máy, sắp xếp nhân sự sau khi chia tách cơ sở 2 Châu Phú để thành lập Trường Trung cấp Kinh tế Kỹ thuật An Giang; xúc tiến thực hiện Đề án thành lập khoa Y.

Hòa nhập với xu thế phát triển chung của các trường đại học trên phạm vi quốc gia, nhà trường không ngừng tăng cường và mở rộng quan hệ hợp tác trong nước, ngoài nước, đẩy mạnh nghiên cứu khoa học chuyển giao công nghệ ... Trường Đại học An Giang sẽ là địa chỉ tin cậy trong công tác giáo dục, đào tạo nguồn nhân lực đáp ứng nhu cầu phát triển kinh tế - xã hội cho tỉnh và khu vực.<br/>
</div>